/*
 *   This file was generated by a tool.
 *   Do not edit it, otherwise the changes will be overwritten.
 */

using System;
using UnityEngine;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.IO;
using WJExcelDataClass;

[Serializable]
public class DataManager //: SingletonTemplate<DataManager>
{
	public sdftt p_sdftt;
	public mmm p_mmm;
	public adtttt p_adtttt;

	public sdfttItem GetSdfttItemByID(Int32 id)
	{
		sdfttItem t = null;
		p_sdftt.Dict.TryGetValue(id, out t);
		if (t == null) Debug.LogError("can't find the id " + id + " in sdftt");
		return t;
	}

	public mmmItem GetMmmItemByID(Int32 id)
	{
		mmmItem t = null;
		p_mmm.Dict.TryGetValue(id, out t);
		if (t == null) Debug.LogError("can't find the id " + id + " in mmm");
		return t;
	}

	public adttttItem GetAdttttItemByID(Int32 id)
	{
		adttttItem t = null;
		p_adtttt.Dict.TryGetValue(id, out t);
		if (t == null) Debug.LogError("can't find the id " + id + " in adtttt");
		return t;
	}

	public void LoadAll()
	{
		p_sdftt = Load("sdftt") as sdftt;
		p_mmm = Load("mmm") as mmm;
		p_adtttt = Load("adtttt") as adtttt;
	}

	private System.Object Load(string name)
	{
		IFormatter f = new BinaryFormatter();
		TextAsset text = Resources.Load<TextAsset>("BinConfigData/" + name);
		Stream s = new MemoryStream(text.bytes);
		System.Object obj = f.Deserialize(s);
		s.Close();
		return obj;
	}
}

