/*
 *   This file was generated by a tool.
 *   Do not edit it, otherwise the changes will be overwritten.
 */

using System;
using UnityEngine;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.IO;
using WJExcelDataClass;

[Serializable]
public class DataManager //: SingletonTemplate<DataManager>
{
	public Sheet1 p_Sheet1;

	public Sheet1Item GetSheet1ItemByID(String id)
	{
		Sheet1Item t = null;
		p_Sheet1.Dict.TryGetValue(id, out t);
		if (t == null) Debug.LogError("can't find the id " + id + " in Sheet1");
		return t;
	}

	public void LoadAll()
	{
		p_Sheet1 = Load("Sheet1") as Sheet1;
	}

	private System.Object Load(string name)
	{
		IFormatter f = new BinaryFormatter();
		TextAsset text = Resources.Load<TextAsset>("BinConfigData/" + name);
		Stream s = new MemoryStream(text.bytes);
		System.Object obj = f.Deserialize(s);
		s.Close();
		return obj;
	}
}

